#define STNOAPPL 29  	/* STRING */
#define STNOWIND 30  	/* STRING */
#define STNOOPEN 31  	/* STRING */
#define STFORMAT 32  	/* STRING */
#define STBADCOP 33  	/* STRING */
#define STNOSTAK 34  	/* STRING */
#define STDELDIS 35  	/* STRING */
#define STAPGONE 37  	/* STRING */
#define STNODRA1 38  	/* STRING */
#define STNODRA2 39  	/* STRING */
#define STFOEXIS 40  	/* STRING */
#define STDISKFU 41  	/* STRING */
#define STNOFILE 42  	/* STRING */
#define STNOINF 43  	/* STRING */
#define STFO8DEE 44  	/* STRING */
#define ADMENU 0  	/* TREE */
#define ADFILEIN 1  	/* TREE */
#define ADDISKIN 2  	/* TREE */
#define ADFOLDIN 3  	/* TREE */
#define ADDINFO 4  	/* TREE */
#define ADTRINFO 5  	/* TREE */
#define ADOPENAP 6  	/* TREE */
#define ADINSDIS 7  	/* TREE */
#define ADINSAPP 8  	/* TREE */
#define ADCOPYDI 9  	/* TREE */
#define ADDELEDI 10  	/* TREE */
#define ADCPALER 11  	/* TREE */
#define ADMKDBOX 12  	/* TREE */
#define ADSETPRE 13  	/* TREE */
#define STINFOST 0		/* FREE STRING */
#define STAPPL 2		/* FREE STRING */
#define STDOCU 3		/* FREE STRING */
#define STDKFRM1 4		/* FREE STRING */
#define STGEMHIC 6		/* FREE STRING */
#define STGEMAPP 7		/* FREE STRING */
#define STGEMLOI 8		/* FREE STRING */
#define STGEMOUT 9		/* FREE STRING */
#define STGEMBAT 10		/* FREE STRING */
#define ST1STD 11		/* FREE STRING */
#define ST2STD 12		/* FREE STRING */
#define ST3STD 13		/* FREE STRING */
#define ST4STD 14		/* FREE STRING */
#define ST5STD 15		/* FREE STRING */
#define ST6STD 16		/* FREE STRING */
#define STASICON 1		/* FREE STRING */
#define FILEMENU 4  	/* OBJECT in TREE #0 */
#define VIEWMENU 6  	/* OBJECT in TREE #0 */
#define OPTNMENU 5  	/* OBJECT in TREE #0 */
#define DESKMENU 3  	/* OBJECT in TREE #0 */
#define ABOUITEM 9  	/* OBJECT in TREE #0 */
#define OPENITEM 18  	/* OBJECT in TREE #0 */
#define SHOWITEM 19  	/* OBJECT in TREE #0 */
#define FORMITEM 25  	/* OBJECT in TREE #0 */
#define OUTPITEM 26  	/* OBJECT in TREE #0 */
#define QUITITEM 27  	/* OBJECT in TREE #0 */
#define NFOLITEM 21  	/* OBJECT in TREE #0 */
#define CLOSITEM 22  	/* OBJECT in TREE #0 */
#define CLSWITEM 23  	/* OBJECT in TREE #0 */
#define L2ITEM 20  	/* OBJECT in TREE #0 */
#define L3ITEM 24  	/* OBJECT in TREE #0 */
#define IDSKITEM 30  	/* OBJECT in TREE #0 */
#define IAPPITEM 31  	/* OBJECT in TREE #0 */
#define L5ITEM 32  	/* OBJECT in TREE #0 */
#define PREFITEM 33  	/* OBJECT in TREE #0 */
#define SAVEITEM 34  	/* OBJECT in TREE #0 */
#define DOSITEM 35  	/* OBJECT in TREE #0 */
#define ICONITEM 37  	/* OBJECT in TREE #0 */
#define TEXTITEM 38  	/* OBJECT in TREE #0 */
#define L4ITEM 39  	/* OBJECT in TREE #0 */
#define NAMEITEM 40  	/* OBJECT in TREE #0 */
#define DATEITEM 41  	/* OBJECT in TREE #0 */
#define SIZEITEM 42  	/* OBJECT in TREE #0 */
#define TYPEITEM 43  	/* OBJECT in TREE #0 */
#define FIOK 2  	/* OBJECT in TREE #1 */
#define FICNCL 3  	/* OBJECT in TREE #1 */
#define FITIME 6  	/* OBJECT in TREE #1 */
#define FIDATE 5  	/* OBJECT in TREE #1 */
#define FISIZE 7  	/* OBJECT in TREE #1 */
#define FINAME 8  	/* OBJECT in TREE #1 */
#define DIDRIVE 4  	/* OBJECT in TREE #2 */
#define DINFOLDS 6  	/* OBJECT in TREE #2 */
#define DIVOLUME 5  	/* OBJECT in TREE #2 */
#define DINFILES 7  	/* OBJECT in TREE #2 */
#define DIUSED 8  	/* OBJECT in TREE #2 */
#define DIAVAIL 9  	/* OBJECT in TREE #2 */
#define DIOK 1  	/* OBJECT in TREE #2 */
#define FOLNAME 4  	/* OBJECT in TREE #3 */
#define FOLDATE 5  	/* OBJECT in TREE #3 */
#define FOLTIME 6  	/* OBJECT in TREE #3 */
#define FOLNFOLD 7  	/* OBJECT in TREE #3 */
#define FOLNFILE 9  	/* OBJECT in TREE #3 */
#define FOLSIZE 8  	/* OBJECT in TREE #3 */
#define FOLOK 1  	/* OBJECT in TREE #3 */
#define DEICON 5  	/* OBJECT in TREE #4 */
#define DEOK 2  	/* OBJECT in TREE #4 */
#define APPLNAME 6  	/* OBJECT in TREE #6 */
#define APPLPARM 5  	/* OBJECT in TREE #6 */
#define APPLOK 1  	/* OBJECT in TREE #6 */
#define APPLCNCL 2  	/* OBJECT in TREE #6 */
#define DRID 6  	/* OBJECT in TREE #7 */
#define DRLABEL 7  	/* OBJECT in TREE #7 */
#define DRTYPE 14  	/* OBJECT in TREE #7 */
#define DRFLOPPY 9  	/* OBJECT in TREE #7 */
#define DRHARD 13  	/* OBJECT in TREE #7 */
#define DRINST 1  	/* OBJECT in TREE #7 */
#define DRREM 2  	/* OBJECT in TREE #7 */
#define DRCNCL 3  	/* OBJECT in TREE #7 */
#define MKNAME 5  	/* OBJECT in TREE #12 */
#define MKOK 1  	/* OBJECT in TREE #12 */
#define MKCNCL 2  	/* OBJECT in TREE #12 */
#define DDFOLDS 5  	/* OBJECT in TREE #10 */
#define DDFILES 6  	/* OBJECT in TREE #10 */
#define DDOK 1  	/* OBJECT in TREE #10 */
#define DDCNCL 2  	/* OBJECT in TREE #10 */
#define TRINFOK 1  	/* OBJECT in TREE #5 */
#define APNAME 8  	/* OBJECT in TREE #8 */
#define APDOCU 26  	/* OBJECT in TREE #8 */
#define APDFTYPE 27  	/* OBJECT in TREE #8 */
#define APTYPE 9  	/* OBJECT in TREE #8 */
#define APGEM 22  	/* OBJECT in TREE #8 */
#define APDOS 23  	/* OBJECT in TREE #8 */
#define APPARMS 24  	/* OBJECT in TREE #8 */
#define APMEM 10  	/* OBJECT in TREE #8 */
#define APFTITLE 12  	/* OBJECT in TREE #8 */
#define APFUPARO 17  	/* OBJECT in TREE #8 */
#define APFDNARO 18  	/* OBJECT in TREE #8 */
#define APINST 3  	/* OBJECT in TREE #8 */
#define APREMV 4  	/* OBJECT in TREE #8 */
#define APCNCL 5  	/* OBJECT in TREE #8 */
#define APFILEBO 13  	/* OBJECT in TREE #8 */
#define APF1NAME 14  	/* OBJECT in TREE #8 */
#define APF2NAME 15  	/* OBJECT in TREE #8 */
#define APSCRLBA 16  	/* OBJECT in TREE #8 */
#define APFSVSLI 19  	/* OBJECT in TREE #8 */
#define APFSVELE 20  	/* OBJECT in TREE #8 */
#define CDFOLDS 5  	/* OBJECT in TREE #9 */
#define CDFILES 6  	/* OBJECT in TREE #9 */
#define CDOK 1  	/* OBJECT in TREE #9 */
#define CDCNCL 2  	/* OBJECT in TREE #9 */
#define CACURRNA 6  	/* OBJECT in TREE #11 */
#define CACOPYNA 7  	/* OBJECT in TREE #11 */
#define CAOK 1  	/* OBJECT in TREE #11 */
#define CACNCL 2  	/* OBJECT in TREE #11 */
#define SPCNFDEL 8  	/* OBJECT in TREE #13 */
#define SPCNFCOP 9  	/* OBJECT in TREE #13 */
#define SPDCLICK 10  	/* OBJECT in TREE #13 */
#define SPDC1 27  	/* OBJECT in TREE #13 */
#define SPDC2 28  	/* OBJECT in TREE #13 */
#define SPDC3 29  	/* OBJECT in TREE #13 */
#define SPDC4 30  	/* OBJECT in TREE #13 */
#define SPDC5 31  	/* OBJECT in TREE #13 */
#define SPOK 4  	/* OBJECT in TREE #13 */
#define SPCNCL 5  	/* OBJECT in TREE #13 */
#define APMEMBOX 1  	/* OBJECT in TREE #8 */
#define INSAPP 6  	/* OBJECT in TREE #8 */
#define SPCD 12  	/* OBJECT in TREE #13 */
#define SPCC 13  	/* OBJECT in TREE #13 */
#define SPSE 14  	/* OBJECT in TREE #13 */
#define SPCO 16  	/* OBJECT in TREE #13 */
#define SPMNCLKY 33  	/* OBJECT in TREE #13 */
#define SPMNCLKN 34  	/* OBJECT in TREE #13 */
#define SPDFMMDD 22  	/* OBJECT in TREE #13 */
#define SPDFDDMM 21  	/* OBJECT in TREE #13 */
#define SPTF24HR 24  	/* OBJECT in TREE #13 */
#define SPTF12HR 25  	/* OBJECT in TREE #13 */
#define STAM 17		/* FREE STRING */
#define STPM 18		/* FREE STRING */
#define CASTOP 4  	/* OBJECT in TREE #11 */
#define APYMEM 35  	/* OBJECT in TREE #8 */
#define FIRO 10  	/* OBJECT in TREE #1 */
#define FIARC 11  	/* OBJECT in TREE #1 */
#define FIHID 12  	/* OBJECT in TREE #1 */
#define FISYS 13  	/* OBJECT in TREE #1 */
#define INFOINNR 4  	/* OBJECT in TREE #4 */
#define AUTHOR1 6  	/* OBJECT in TREE #4 */
#define AUTHOR2 7  	/* OBJECT in TREE #4 */
#define AUTHOR3 8  	/* OBJECT in TREE #4 */
#define AUTHOR4 9  	/* OBJECT in TREE #4 */
#define AUTHOR5 11  	/* OBJECT in TREE #4 */
#define AUTHOR6 14  	/* OBJECT in TREE #4 */
#define AUTHOR7 15  	/* OBJECT in TREE #4 */
#define AUTHOR8 16  	/* OBJECT in TREE #4 */
#define TYPITEM 28  	/* OBJECT in TREE #0 */
#define STFSCAN 19		/* FREE STRING */
#define STFBYTES 20		/* FREE STRING */
#define STFWORDS 21		/* FREE STRING */
#define STBADOPN 36  	/* STRING */
#define STEMPTY 45  	/* STRING */
#define STNOMEM 46  	/* STRING */
#define DRCD 10  	/* OBJECT in TREE #7 */
#define DRNET 11  	/* OBJECT in TREE #7 */
#define DR5QRTR 12  	/* OBJECT in TREE #7 */
#define DRVTFLOP 22		/* FREE STRING */
#define DRVTHARD 23		/* FREE STRING */
#define DRVTNET 24		/* FREE STRING */
#define DRVTCD 25		/* FREE STRING */
#define DRVTREM 26		/* FREE STRING */
#define DRVTUNKN 27		/* FREE STRING */
#define DRVCLINE 28		/* FREE STRING */
#define SPNOSCAN 36  	/* OBJECT in TREE #13 */
#define SPNONET 38  	/* OBJECT in TREE #13 */
#define STDEEPPA 47  	/* STRING */
