#
# Location of Open Watcom libraries
#
include ../makedefs.i

SOURCE = ems_all.c ems_fp.c ems_free.c ems_fs.c ems_map.c ems_np.c \
	 ems_rmap.c ems_smap.c ems_vers.c emslib.c ev_event.c formdo.c \
	 ob_dofl.c ob_dost.c ob_dr_di.c ob_g_txt.c ob_isfl.c ob_isst.c \
	 ob_s_txt.c ob_ud_di.c ob_udfl.c ob_udst.c ob_xywh.c wccd000.c \
	 wccd001.c wccd002.c wccd003.c wccd004.c wccd005.c wccd006.c \
	 wccd007.c wccd008.c wccd009.c wccd010.c wccd011.c wccd012.c \
	 wccd013.c wccd014.c wccd015.c wccd016.c wccd017.c wccd018.c \
	 wccd019.c wccd020.c wccd021.c wccd022.c wccd023.c wccd024.c \
	 wccd025.c wccd026.c wccd027.c wccd028.c wccfdraw.c wccg000.c \
	 wccg001.c wccg002.c wccg003.c wccg004.c wccg005.c wccg006.c \
	 wccg007.c wccg008.c wccg009.c wccg010.c wccg011.c wccg012.c \
	 wccg013.c wccg014.c wccg015.c wccg016.c wccg017.c wccg018.c \
	 wccg019.c wccg020.c wccg021.c wccg022.c wccg023.c wccg024.c \
	 wccg025.c wccg026.c wccg027.c wccg028.c wccg029.c wccg030.c \
	 wccg031.c wccg032.c wccg033.c wccg034.c wccg035.c wccg036.c \
	 wccg037.c wccg038.c wccg039.c wccg040.c wccg041.c wccg042.c \
	 wccg043.c wccg044.c wccg045.c wccg046.c wccg047.c wccg048.c \
	 wccg049.c wccg050.c wccg051.c wccg052.c wccg053.c wccg054.c \
	 wccg055.c wccg056.c wccg057.c wccg058.c wccg059.c wccg060.c \
	 wccg061.c wccg062.c wccg063.c wccg064.c wccg065.c wccg066.c \
	 wccg067.c wccg068.c wccg069.c wccg070.c wccg071.c wccg072.c \
	 wccg073.c wccg074.c wccg075.c wccg076.c wccg077.c wccg078.c \
	 wccg079.c wccg080.c wccg081.c wccg082.c wccg083.c wccg084.c \
	 wccg085.c wccg086.c wccg087.c wccg088.c wccg089.c wccg090.c \
	 wccgcrt.c wccgem.c wcchook.c wcclptr.c \
	 wccv000.c wccv001.c wccv002.c wccv003.c wccv004.c wccv005.c \
	 wccv006.c wccv007.c wccv008.c wccv009.c wccv010.c wccv011.c \
	 wccv012.c wccv013.c wccv014.c wccv015.c wccv016.c wccv017.c \
	 wccv018.c wccv019.c wccv020.c wccv021.c wccv022.c wccv023.c \
	 wccv024.c wccv025.c wccv026.c wccv027.c wccv028.c wccv029.c \
	 wccv030.c wccv031.c wccv032.c wccv033.c wccv034.c wccv035.c \
	 wccv036.c wccv037.c wccv038.c wccv039.c wccv040.c wccv041.c \
	 wccv042.c wccv043.c wccv044.c wccv045.c wccv046.c wccv047.c \
	 wccv048.c wccv049.c wccv050.c wccv051.c wccv052.c wccv053.c \
	 wccv054.c wccv055.c wccv056.c wccv057.c wccv058.c wccv059.c \
	 wccv060.c wccv061.c wccv062.c wccv063.c wccv064.c wccv065.c \
	 wccv066.c wccv067.c wccv068.c wccv069.c wccv070.c wccv071.c \
	 wccv072.c wccv073.c wccv074.c wccv075.c wccv076.c wccv077.c \
	 wccv078.c wccv079.c wccv080.c wccv081.c wccv082.c wccv083.c \
	 wccv084.c wccv085.c wccv086.c wccv087.c wccv088.c wccv089.c \
	 wccv090.c wccv091.c wccv092.c wccv093.c wccv094.c wccv095.c \
	 wccv096.c wccv097.c wccv098.c wccv099.c wccv100.c wccv101.c \
	 wccv102.c wccv103.c wccv104.c wccv105.c wccv106.c wccv107.c \
	 wccv108.c wccv109.c wccv110.c wccv111.c wccv112.c wccv113.c \
	 wccv114.c wccv115.c wccv116.c wccv117.c wccv118.c wccv119.c \
	 wccv120.c wccv121.c wccv122.c wccv123.c wccv124.c wccv125.c \
	 wccv126.c wccv127.c wccv128.c wccv129.c wccv130.c wccv131.c \
	 wccv132.c wccv133.c wccv134.c wccv135.c wccv136.c wccv137.c \
	 wccv138.c wccvdi.c rc_copy.c rc_equal.c rc_gr2ar.c \
	 rc_insid.c rc_inter.c trimage.c x_dux_sc.c x_dux_xf.c x_duy_sc.c \
	 x_duy_xf.c x_mul_di.c x_saspec.c x_sxform.c x_udx_sc.c x_udx_xf.c \
	 x_udx_yf.c x_udy_sc.c x_ytox.c xfmlib.c

all:	../lib/wccgem-l.lib ../lib/wccgem-s.lib

../lib/wccgem-l.lib: large/wccgem-l.lib 
	cp large/wccgem-l.lib ../lib/wccgem-l.lib

../lib/wccgem-s.lib: small/wccgem-s.lib
	cp small/wccgem-s.lib ../lib/wccgem-s.lib

large/wccgem-l.lib: $(SOURCE)
	$(MAKE) -C large

small/wccgem-s.lib: $(SOURCE)
	$(MAKE) -C small

large/wccgem-c.lib: $(SOURCE)
	$(MAKE) -C compact

small/wccgem-m.lib: $(SOURCE)
	$(MAKE) -C medium

small/wccgem-h.lib: $(SOURCE)
	$(MAKE) -C huge

tidy:
	rm -f *.bak
	rm -f *.err
	$(MAKE) -C small tidy
	$(MAKE) -C large tidy
	$(MAKE) -C compact tidy
	$(MAKE) -C medium tidy
	$(MAKE) -C huge tidy

clean:	
	rm -f ../lib/wccgem-l.lib 
	rm -f ../lib/wccgem-s.lib
	rm -f *.bak
	rm -f *.err
	$(MAKE) -C small clean
	$(MAKE) -C large clean
	$(MAKE) -C compact clean
	$(MAKE) -C medium clean
	$(MAKE) -C huge clean
